### ISSUE TITLE
Basic how h11 was working

### ISSUE THREAD

**Issue by blackshirt** [njsmith/h11#45]
I'm trying to grasp h11 how it working, here when i construct and build request manually, and send it over ssl socket. I think it works normally, 

```python
Python` 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:53:44) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h11, socket, ssl
>>> ctx = ssl.create_default_context()
>>> sock = ctx.wrap_socket(socket.create_connection(("httpbin.org", 443)), server_hostname="httpbin.org")
>>> sock.sendall(b"GET /get HTTP/1.1\r\nhost: httpbin.org\r\n\r\n")
>>> data = sock.recv(1024)
>>> data
b'HTTP/1.1 200 OK\r\nConnection: keep-alive\r\nServer: gunicorn/19.7.1\r\nDate: Sat, 15 Apr 2017 02:26:31 GMT\r\nContent-Type: application/json\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nContent-Length: 160\r\nVia: 1.1 vegur\r\n\r\n{\n  "args": {}, \n  "headers": {\n    "Connection": "close", \n    "Host": "httpbin.org"\n  }, \n  "origin": "112.215.153.61", \n  "url": "https://httpbin.org/get"\n}\n'
>>> print(data.decode('ascii'))
HTTP/1.1 200 OK
Connection: keep-alive
Server: gunicorn/19.7.1
Date: Sat, 15 Apr 2017 02:26:31 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Length: 160
Via: 1.1 vegur

{
  "args": {}, 
  "headers": {
    "Connection": "close", 
    "Host": "httpbin.org"
  }, 
  "origin": "112.215.153.61", 
  "url": "https://httpbin.org/get"
}

>>>
```

Here where i'm trying to use h11 construct .. i'm using examples from the official docs, so ..its should works normally too

```python
>>> import ssl, socket, h11
>>> ctx = ssl.create_default_context()
>>> sock = ctx.wrap_socket(socket.create_connection(("httpbin.org", 443)), server_hostname="httpbin.org")
>>> conn = h11.Connection(our_role=h11.CLIENT)
>>> req = h11.Request(method="GET", target="/get", headers=[("Host", "httpbin,org")])
>>> btosend = conn.send(req)
>>> sock.sendall(btosend)
>>> sock.sendall(conn.send(h11.EndOfMessage()))
>>> data = sock.recv(1024)
>>> conn.receive_data(data)
>>> conn.next_event()
Traceback (most recent call last):
  File "/home/simbah/miniconda3/lib/python3.6/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simbah/miniconda3/lib/python3.6/site-packages/h11/_connection.py", line 439, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/home/simbah/miniconda3/lib/python3.6/site-packages/h11/_util.py", line 71, in _reraise_as_remote_protocol_error
    raise self
  File "/home/simbah/miniconda3/lib/python3.6/site-packages/h11/_connection.py", line 422, in next_event
    self._process_event(self.their_role, event)
  File "/home/simbah/miniconda3/lib/python3.6/site-packages/h11/_connection.py", line 238, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "/home/simbah/miniconda3/lib/python3.6/site-packages/h11/_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "/home/simbah/miniconda3/lib/python3.6/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
    .format(event_type, role, self.states[role]))
h11._util.RemoteProtocolError: can't handle event type <class 'h11._events.ConnectionClosed'> for SERVER in state SEND_RESPONSE
>>> 
```

Whats the problem was ... ? 

Thanks

**Comment by njsmith** [comment]
Your call to `sock.recv` returned an empty string, which is how `sock.recv` indicates that the remote host has closed the connection. (If you're typing this at the REPL, this probably happened because you didn't type fast enough and the remote host got tired of waiting for you 😄). Then you passed this to `conn.receive_data`, which interprets an empty string as meaning that the remote host has closed the connection. This caused h11 to raise `RemoteProtocolError`, to let you know that something has gone wrong – we were expecting the remote host to send a response, not just rudely close the connection.

I worked this out from the message at the end – h11's parser interpreted the data you gave it as a `ConnectionClosed` event, which isn't something it expects from a `SERVER` in state `SEND_RESPONSE` (which is the name for the protocol state where we're expecting the server to, well, send a response).

(Note also that you also misspelled the `Host:` header, but that should get you a 404, not a connection drop.)

I should probably put a note in the tutorial about this failure mode...

**Comment by njsmith** [comment]
Also FYI, putting triple-backticks around a block of code makes it render as code, instead of github trying to interpret it as markdown – I fixed your post here, but it's a useful github tip in general :-)
